### ISSUE TITLE
Is this a virus?

### ISSUE THREAD

**Issue by lory-dev** [ipwnosx/XyliaseGeneratorV1-Cracked#3]
I dont know if its a virus please tell me

**Comment by lory-dev** [comment]
![image](https://user-images.githubusercontent.com/91797315/152388559-7a02715c-7c99-4bec-b9f3-084f0f119618.png)

**Comment by tarekesam82** [comment]
What do you think?

**Comment by ipwnosx** [comment]
Well if virus total says no… what do you think??

**Comment by ipwnosx** [comment]
I doubt this works anymore.
